import type { Metadata } from 'next'
import Image from 'next/image'
import Link from 'next/link'

export const metadata: Metadata = {
  title: 'West Hyderabad Schools Practical Guide (2026)',
  description: 'Curriculum pathways fees campus context and practical comparisons for returning NRI families.',
  alternates: { canonical: 'https://www.returningnris.com/resources/west-hyderabad-schools-practical-guide' },
}

type Profile = { name: string; curriculum: string; fit: string; campus: string; watch: string }
const profiles: { heading: string; schools: Profile[] }[] = [
  { heading: 'Ultra premium and expat benchmarks', schools: [
    { name: 'International School of Hyderabad', curriculum: 'U.S. Common Core and AERO in the earlier years, Cambridge IGCSE in Grades 9 and 10, and IBDP in Grades 11 and 12.', fit: 'The strongest fit in this set for children moving from a U.S. or highly international school environment. It has a small, globally diverse community and a low-key academic culture.', campus: 'Located within the ICRISAT campus, with a mature green setting and access to sports and learning facilities. The environment is less commercial and more internationally oriented than most large city schools.', watch: 'The commute from the core Financial District, Kokapet and Gachibowli belt can be long. Indian-citizen admissions may be limited, and the fee sits at the top of the market.' },
    { name: 'The Shri Ram Academy', curriculum: 'Authorized IB Primary Years Programme and Middle Years Programme. The school states that it is a candidate for IBDP and IBCP.', fit: 'A strong fit for families seeking small cohorts, personalized attention and the Shri approach to inquiry-led learning close to the Financial District.', campus: "Modern, intentionally designed learning spaces with a boutique feel. Smaller batches are a key differentiator, but the fee is high relative to the school's age.", watch: 'This is a young campus with limited operating history. Families entering senior grades should verify the authorization timeline, cohort size and final Grade 11 and 12 pathway.' },
    { name: 'Indus International School', curriculum: 'Authorized IB PYP, MYP, DP and CP pathway.', fit: 'A leading option for families seeking a complete IB journey, a strong leadership programme and day-cum-boarding flexibility.', campus: 'Large destination campus with substantial sports, leadership and residential facilities. Its boarding culture distinguishes it from most West Hyderabad day schools.', watch: 'The campus is far from the core tech hubs. Daily commute time should be tested at actual school-bus hours before admission.' },
  ] },
  { heading: 'High volume legacy schools', schools: [
    { name: 'CHIREC International School', curriculum: 'CBSE through Grade 12, plus a Cambridge pathway through IGCSE followed by IBDP in Grades 11 and 12.', fit: 'A mature academic brand with strong local recognition, competitive peer groups and established board preparation. It suits families that value track record and access to a large alumni community.', campus: 'Established urban campuses with strong academic and activity infrastructure. Its central West Hyderabad location is a major practical advantage.', watch: 'Large cohorts and a corporate operating structure may feel less personal than a smaller school. Confirm the campus and curriculum stream tied to the offered seat.' },
    { name: 'Oakridge International School Gachibowli', curriculum: 'IB PYP, MYP and DP, plus CBSE from Grade 7 through Grade 12. The current official curriculum page does not list Cambridge for the Gachibowli campus.', fit: 'A broad international-school experience within the Nord Anglia network, with structured co-curricular activities and a mature university preparation system.', campus: 'Large urban campus with extensive activity and sports infrastructure, serving a high student volume near the Financial District and Gachibowli corridor.', watch: "The school operates at significant scale, so families should ask about section size, counsellor access and the experience of their child's specific grade." },
    { name: 'Sreenidhi International School', curriculum: 'IB PYP, MYP, DP and CP. The current school site presents Sreenidhi as an IB school rather than a Cambridge pathway school.', fit: 'A mature full-IB school with day and boarding options, a strong campus environment and specialized sports facilities.', campus: 'Large established campus with extensive sports, arts and residential facilities. It offers a destination-school experience rather than a compact neighborhood model.', watch: 'The campus is outside the core West Hyderabad residential belt. Test commute time and confirm whether day, weekly boarding or full boarding best suits the family.' },
  ] },
  { heading: 'Academically solid and practical value', schools: [
    { name: 'Meru International School Tellapur', curriculum: 'CBSE through Grade 12 and Cambridge through IGCSE. Confirm the exact entry grade and senior-school path for the current admission year.', fit: 'A convenient neighborhood option for families in Tellapur, Nallagandla and nearby gated communities. It combines structured academics with sports, values and technology-led programmes.', campus: 'Modern campus close to large residential communities, with a practical balance of facilities and commute.', watch: 'The Tellapur campus is newer than the Miyapur branch.' },
    { name: 'Manthan International School', curriculum: 'Students choose Cambridge IGCSE and A Levels or CBSE from Grade 8. Earlier grades follow the school\'s common learning programme.', fit: 'A strong fit for parents who prioritize classroom learning, smaller learning groups and inclusion over a very large sports campus. It offers a clear Cambridge or CBSE choice in the senior years.', campus: 'A learning-focused campus with a reputation for close teacher interaction and a more intimate school environment.', watch: 'Its physical sports infrastructure is more modest than the large destination campuses.' },
    { name: 'Sancta Maria International School', curriculum: 'Full Cambridge pathway from Early Years through IGCSE and AS and A Levels.', fit: 'One of the clearest choices in West Hyderabad for families committed to Cambridge through Grade 12. It is known for a disciplined learning environment and transparent day-to-day administration.', campus: 'Clean, established campus with balanced academics and sports. It feels more focused and less sprawling than the largest residential-style schools.', watch: 'It does not offer CBSE or IB, so families should be comfortable committing to Cambridge.' },
    { name: 'Phoenix Greens School of Learning', curriculum: 'CBSE through Grade 12 and Cambridge from Primary through IGCSE. Recent school pages differ on whether A Levels are currently available, so confirm the Grade 11 and 12 route directly.', fit: 'A value-oriented option with a grounded learning environment and convenient access for Kokapet, Narsingi and Financial District families.', campus: 'Compact urban campus with a collaborative feel. Its appeal is academic value and location rather than a very large green footprint.', watch: 'The campus is smaller than the large destination schools. Confirm Cambridge continuation beyond IGCSE.' },
    { name: 'Rockwell International School', curriculum: 'CBSE through Grade 12, Cambridge through IGCSE and authorized IBDP in Grades 11 and 12.', fit: 'A practical multi-curriculum choice for families who want short commutes from Kokapet and the Financial District while retaining CBSE, Cambridge and IB Diploma options.', campus: 'Urban, accessible campus positioned close to major West Hyderabad residential and technology corridors.', watch: 'The campus is compact and has less open green space than Indus, Sreenidhi or The Gaudium.' },
  ] },
  { heading: 'Infrastructure heavy and rapidly growing schools', schools: [
    { name: 'The Gaudium School', curriculum: 'IB PYP in Nursery to Grade 5; IB MYP, Cambridge or CBSE in Grades 6 to 10; and IBDP, Cambridge AS and A Levels or CBSE in Grades 11 and 12.', fit: 'The broadest curriculum choice in this set, with major sports infrastructure and boarding. It suits families who want one campus to support different pathways for siblings.', campus: 'A 27-acre green campus with substantial sports, arts, laboratories and boarding infrastructure.', watch: 'Fast growth can create a busy campus experience. Compare section size, teacher stability and travel time for the specific grade and route.' },
    { name: 'Birla Open Minds International School', curriculum: 'CBSE through Grade 12; Cambridge from Grades 1 to 10; and the IB Career-related Programme in Grades 11 and 12 for the international route.', fit: 'A broad, established multi-curriculum option with extensive infrastructure, career counselling and a practical bridge from Cambridge into IBCP.', campus: 'A 10-acre campus with sports complex, pool, auditorium, laboratories and green-building credentials. The school serves a high student volume.', watch: "The international senior pathway is IBCP, not the traditional IBDP. Families should understand the career-related study component and compare it with A Levels or IBDP for their child's university plans." },
  ] },
]

const overview = [
  ['International School of Hyderabad', 'Patancheru', '1981  45 years', 'INR 7.5-12.0 lakh+', 'Ultra-premium and expat'], ['The Shri Ram Academy', 'Gowlidoddy', '2023  3 years', 'INR 5.0-7.5 lakh+', 'Ultra-premium and boutique'], ['Indus International School', 'Shankarpally', '2008  18 years', 'INR 5.5-9.5 lakh+', 'Ultra-premium and boarding'], ['CHIREC International School', 'Kondapur', '1989  37 years', 'INR 3.5-7.5 lakh+', 'High-volume legacy'], ['Oakridge International School', 'Gachibowli', '2001  25 years', 'INR 4.5-9.0 lakh+', 'High-volume legacy'], ['Sreenidhi International School', 'Moinabad and Aziznagar', '2003  23 years', 'INR 5.5-9.5 lakh', 'High-volume legacy'], ['Meru International School', 'Tellapur', '2022 campus  4 years', 'INR 2.8-4.2 lakh', 'Practical value'], ['Manthan International School', 'Tellapur', '2009  17 years', 'INR 3.0-5.0 lakh', 'Practical value'], ['Sancta Maria International School', 'Serilingampally', '2011  15 years', 'INR 3.5-5.5 lakh', 'Practical value'], ['Phoenix Greens School of Learning', 'Kokapet', '2013  13 years', 'INR 3.1-3.8 lakh', 'Practical value'], ['Rockwell International School', 'Kokapet', '2009  17 years', 'INR 2.8-3.8 lakh', 'Practical value'], ['The Gaudium School', 'Kollur', '2015  11 years', 'INR 3.5-5.5 lakh', 'Infrastructure and growth'], ['Birla Open Minds International', 'Kollur', '2013  13 years', 'INR 3.0-4.5 lakh', 'Infrastructure and growth'],
]

const priorities = [
  ['Closest continuity from a U.S. school', 'International School of Hyderabad', 'U.S. and AERO pathway before IGCSE and IBDP'], ['Full IB continuum', 'Indus, Oakridge, Sreenidhi, The Gaudium', 'PYP, MYP and DP are available; Indus and Sreenidhi also list CP'], ['Small IB environment', 'The Shri Ram Academy', 'Boutique setting; authorized PYP and MYP; DP and CP candidacy'], ['Full Cambridge through A Levels', 'Sancta Maria, Manthan, The Gaudium', 'Clear senior-school continuation; The Gaudium begins Cambridge in Grade 6'], ['CBSE plus an international route', 'CHIREC, Oakridge, Meru, Manthan, Phoenix Greens, Rockwell, The Gaudium, Birla Open Minds', 'Allows different pathways, but entry grades vary'], ['Large campus and sports', 'Indus, Sreenidhi, The Gaudium, Birla Open Minds', 'Destination campuses; test commute or boarding fit'], ['Central West Hyderabad access', 'CHIREC, Oakridge, The Shri Ram Academy, Phoenix Greens, Rockwell', 'More practical for many Kondapur, Gachibowli, Kokapet and Financial District homes'], ['Tellapur and Nallagandla convenience', 'Meru, Manthan', 'Neighborhood access with CBSE and Cambridge options'],
]
const ibRows = [
  ['International School of Hyderabad', 'U.S. and AERO', 'U.S. AERO and IGCSE', 'IBDP', 'DP-only IB pathway'], ['The Shri Ram Academy', 'PYP', 'MYP', 'DP and CP candidate', 'Authorized PYP and MYP'], ['Indus International', 'PYP', 'MYP', 'DP and CP', 'Full IB continuum'], ['CHIREC International', 'Cambridge or CBSE', 'Cambridge or CBSE', 'IBDP or CBSE', 'DP after Cambridge route'], ['Oakridge Gachibowli', 'PYP', 'MYP', 'DP', 'Full IB continuum plus CBSE'], ['Sreenidhi International', 'PYP', 'MYP', 'DP and CP', 'Full IB continuum'], ['Rockwell International', 'Cambridge or CBSE', 'Cambridge or CBSE', 'IBDP or CBSE', 'DP-only IB pathway'], ['The Gaudium', 'PYP', 'MYP', 'DP', 'Full IB continuum'], ['Birla Open Minds', 'Cambridge or CBSE', 'Cambridge or CBSE', 'IBCP or CBSE', 'Career-related Programme'],
]
const cambridgeRows = [
  ['International School of Hyderabad', 'U.S. curriculum', 'U.S. AERO', 'Cambridge IGCSE', 'IBDP', 'IGCSE bridge'], ['CHIREC International', 'Cambridge', 'Cambridge', 'Cambridge IGCSE', 'IBDP', 'Cambridge to IB'], ['Meru International', 'Cambridge', 'Cambridge', 'Cambridge IGCSE', 'CBSE', 'Up to IGCSE'], ['Manthan International', 'Cambridge', 'Cambridge', 'Cambridge IGCSE', 'Cambridge (AS & A)', 'Cambridge through Grade 12'], ['Sancta Maria International', 'Cambridge', 'Cambridge', 'Cambridge IGCSE', 'Cambridge (AS & A)', 'Full Cambridge pathway'], ['Phoenix Greens', 'Cambridge', 'Cambridge', 'Cambridge IGCSE', 'Cambridge (AS & A)', 'Full Cambridge pathway'], ['Rockwell International', 'Cambridge', 'Cambridge', 'Cambridge IGCSE', 'IBDP or CBSE', 'Up to IGCSE'], ['The Gaudium', 'IB PYP', 'Cambridge available', 'Cambridge IGCSE', 'Cambridge (AS & A)', 'Cambridge from Grade 6'], ['Birla Open Minds', 'Cambridge', 'Cambridge', 'Cambridge IGCSE', 'IBCP', 'Cambridge to IBCP'],
]
const cbseRows = [
  ['CHIREC International', 'Yes', 'Yes', 'Yes', 'Yes', 'Separate CBSE pathway'], ['Oakridge Gachibowli', 'No', 'From Grade 7', 'Yes', 'Yes', 'CBSE begins in Grade 7'], ['Meru International', 'Yes', 'Yes', 'Yes', 'Yes', 'CBSE through Grade 12'], ['Manthan International', 'No', 'From Grade 8', 'Yes', 'Yes', 'Choice begins in Grade 8'], ['Phoenix Greens', 'Yes', 'Yes', 'Yes', 'Yes', 'CBSE through Grade 12'], ['Rockwell International', 'Yes', 'Yes', 'Yes', 'Yes', 'CBSE through Grade 12'], ['The Gaudium', 'IB PYP', 'From Grade 6', 'Yes', 'Yes', 'CBSE begins in Grade 6'], ['Birla Open Minds', 'Yes', 'Yes', 'Yes', 'Yes', 'CBSE through Grade 12'],
]
const prose: React.CSSProperties = { maxWidth: 980, margin: '0 auto', fontFamily: 'DM Sans, sans-serif', color: '#3D3229' }
function Cards({ headers, rows }: { headers: string[]; rows: string[][] }) { return <div className="cards">{rows.map((row) => <section key={row[0]}><h4>{row[0]}</h4>{row.slice(1).map((item, index) => <p key={headers[index + 1]}><b>{headers[index + 1]}</b>{item}</p>)}</section>)}</div> }

export default function WestHyderabadSchoolsPracticalGuide() {
  return <>
    <section className="hero"><div style={prose}><nav><Link href="/">Home</Link><span>›</span><Link href="/resources">Guides</Link><span>›</span><span>West Hyderabad Schools</span></nav><p className="eyebrow">Schools • Last reviewed 13 September 2026</p><h1>West Hyderabad Schools - Practical Guide</h1><p className="subtitle">Curriculum pathways fees campus context and practical comparisons for returning NRI families</p></div></section>
    <section className="image-shell"><div className="hero-image"><Image src="/resources/west-hyderabad-schools-practical-guide.webp" alt="West Hyderabad Schools Guide" width={1600} height={900} priority quality={72} sizes="(max-width: 640px) 100vw, (max-width: 1000px) 92vw, 980px" style={{ display: 'block', width: '100%', height: 'auto' }} /></div></section>
    <article>
      <section className="intro"><div style={prose}><p>Start with the curriculum, then test the daily reality. This guide compares 13 established and fast-growing schools serving West Hyderabad. It combines curriculum pathways with estimated fees, school maturity, campus context, commute trade-offs and practical fit so families can build a focused shortlist before visiting campuses.</p><p>The main conclusion. No single school leads on every factor. International School of Hyderabad is the clearest option for U.S. curriculum continuity; Indus, Oakridge, Sreenidhi and The Gaudium provide the broadest authorized IB pathways; Sancta Maria and Manthan stand out for Cambridge continuity; and several West Hyderabad schools offer CBSE alongside an international route.</p><p>Fee ranges are benchmark estimates for tuition and recurring annual charges. They can vary by grade and may exclude admission fees, transport, meals, uniforms, devices, deposits and boarding. Confirm the current all-in fee and curriculum availability directly with the school.</p></div></section>
      <section className="section"><div style={prose}><h2>How to use this guide</h2><ol><li>Choose the curriculum pathway that best protects continuity for your child&apos;s current grade and likely university destination.</li><li>Shortlist schools within a realistic commute from home. In West Hyderabad, a school-bus journey can matter more to daily family life than a small difference in facilities.</li><li>Compare the all-in cost, class size, teacher continuity, learning support, language options and grade-specific board authorization before paying an admission fee.</li></ol><h2>Guide structure</h2><ul><li>School and fee overview</li><li>IB curriculum benchmark</li><li>Cambridge curriculum benchmark</li><li>CBSE curriculum benchmark</li><li>Detailed school profiles by practical segment</li><li>Shortlist recommendations and campus visit checklist</li></ul></div></section>
      <section className="section tint"><div style={prose}><h2>Curriculum snapshot</h2><div className="snapshot"><div><h3>IB</h3><p><b>Usually suits</b> Students seeking inquiry-led learning and global university mobility</p><p><b>Strengths</b> Research, interdisciplinary learning and internationally recognized senior programmes</p><p><b>Check before choosing</b> Exact authorization by programme; DP workload; university counselling; grade of entry</p></div><div><h3>Cambridge</h3><p><b>Usually suits</b> Families wanting an international exam pathway with subject choice</p><p><b>Strengths</b> Clear stages, IGCSE and flexible AS and A Level combinations</p><p><b>Check before choosing</b> Whether the school continues through A Levels or stops at IGCSE</p></div><div><h3>CBSE</h3><p><b>Usually suits</b> Families likely to pursue Indian higher education or national entrance tests</p><p><b>Strengths</b> India-aligned content, broad recognition and easier continuity across Indian cities</p><p><b>Check before choosing</b> Teaching style, second and third languages, board preparation and section size</p></div><div><h3>U.S. and AERO</h3><p><b>Usually suits</b> Children transferring from a U.S. school system</p><p><b>Strengths</b> Familiar standards and a smoother early transition</p><p><b>Check before choosing</b> How the pathway changes in Grades 9 to 12</p></div></div></div></section>
      <section className="section"><div style={prose}><h2>School and fee overview</h2><p>The practical segments below are positioning groups, not absolute rankings. A younger or smaller school may suit a child better than a higher-fee legacy campus, especially when commute and classroom fit are stronger.</p><Cards headers={['School', 'Location', 'Established', 'Estimated annual fee', 'Practical segment']} rows={overview} /></div></section>
      <section className="section"><div style={prose}><h2>IB curriculum benchmark</h2><p>Best for global continuity. A full IB continuum reduces the number of curriculum switches from primary school through Grade 12. A school offering only the Diploma Programme can still be an excellent senior-school choice, but the transition into the DP should be evaluated carefully.</p><p><b>IB shortlist by need</b><br />Full IB continuum: Indus, Oakridge, Sreenidhi and The Gaudium.<br />Smaller and newer IB environment: The Shri Ram Academy, currently authorized for PYP and MYP with DP and CP candidacy.</p></div></section>
      <section className="section"><div style={prose}><Cards headers={['School', 'Primary', 'Middle', 'Grades 11 and 12', 'IB position']} rows={ibRows} /></div></section>
      <section className="section tint"><div style={prose}><h2>Cambridge curriculum IGCSE benchmark</h2><p>Best for a structured international exam pathway. Cambridge can offer continuity from Primary through AS and A Levels, but some schools stop at IGCSE and then move students into IBDP, IBCP or CBSE. The senior-school destination matters as much as the curriculum offered today.</p><p><b>Cambridge shortlist by need</b><br />Full Cambridge through A Levels: Sancta Maria and Manthan provide the clearest continuous pathways in this comparison. The Gaudium offers Cambridge from Grade 6 through A Levels.<br />Cambridge through IGCSE followed by IBDP: CHIREC and Rockwell. ISH follows a U.S. pathway before IGCSE and IBDP.<br />Cambridge plus CBSE flexibility: Meru, Manthan, Phoenix Greens, Rockwell, The Gaudium and Birla Open Minds.</p></div></section>
      <section className="section tint"><div style={prose}><Cards headers={['School', 'Primary', 'Lower secondary', 'Grades 9 and 10', 'Grades 11 and 12', 'Pathway']} rows={cambridgeRows} /></div></section>
      <section className="section"><div style={prose}><h2>CBSE curriculum benchmark</h2><p>Best for India-aligned continuity. CBSE is often the more direct fit for families expecting Indian entrance examinations or future moves within India. The important question is not only whether CBSE is available, but also the grade at which students enter the pathway.</p><p><b>CBSE shortlist by need</b><br />CBSE from primary through Grade 12: CHIREC, Meru, Phoenix Greens, Rockwell and Birla Open Minds.<br />Later transition into CBSE: The Gaudium from Grade 6, Oakridge from Grade 7 and Manthan from Grade 8.</p></div></section>
      <section className="section"><div style={prose}><Cards headers={['School', 'Primary', 'Middle', 'Secondary', 'Senior secondary', 'Pathway note']} rows={cbseRows} /></div></section>
      <section className="section tint"><div style={prose}><h2>Detailed school profiles</h2>{profiles.map((group) => <div className="profile-group" key={group.heading}><h3>{group.heading}</h3><div className="profiles">{group.schools.map((school) => <section className="profile" key={school.name}><h4>{school.name}</h4><p><b>Curriculum</b> {school.curriculum}</p><p><b>Practical fit</b> {school.fit}</p><p><b>Campus and environment</b> {school.campus}</p><p><b>Watch for</b> {school.watch}</p></section>)}</div></div>)}</div></section>
      <section className="section"><div style={prose}><h2>Shortlist by family priority</h2><Cards headers={['Family priority', 'Schools to examine first', 'Why']} rows={priorities} /></div></section>
      <section className="section dark"><div style={prose}><h2>A realistic decision order</h2><ol><li>Curriculum continuity for the child&apos;s current grade</li><li>Daily commute at school start and return times</li><li>Classroom fit, teacher quality and learning support</li><li>All-in annual cost and likely fee escalation</li><li>Campus, sports and activities that the child will actually use</li><li>Senior-school subjects, board results and university counselling</li></ol></div></section>
      <section className="section"><div style={prose}><h2>Editorial disclaimer</h2><p>This is an independent planning guide and not an official ranking, endorsement or admission guarantee. School fees, curricula, affiliations, facilities, policies, results and seat availability can change. Parents should verify current information directly with the school and the relevant board or programme directory before making a financial or admission decision.</p></div></section>
    </article>
    <style>{`
      .hero{padding:4rem 1.25rem 2.35rem;background:radial-gradient(ellipse 65% 75% at 14% 5%,rgba(255,153,51,.15),transparent 65%),radial-gradient(ellipse 55% 65% at 95% 50%,rgba(19,136,8,.1),transparent 70%),#fffdf9}.hero nav{display:flex;gap:.45rem;flex-wrap:wrap;font-size:.77rem;margin-bottom:1.45rem;color:#918273}.hero nav a{color:#786A5C;text-decoration:none}.eyebrow{color:#B06000;text-transform:uppercase;letter-spacing:.08em;font-size:.7rem;font-weight:700;margin:0}.hero h1{font:400 clamp(2.2rem,5.2vw,4rem)/1.06 'DM Serif Display',serif;letter-spacing:-.03em;color:#1A1208;margin:1rem 0 .7rem}.subtitle{color:#6B5E50;font-size:clamp(1rem,2vw,1.15rem);line-height:1.65;margin:0}.image-shell{padding:0 1.25rem 3rem;background:#fffdf9}.hero-image{max-width:980px;margin:0 auto;overflow:hidden;border-radius:18px;background:#F8F5F0;box-shadow:0 17px 42px rgba(47,31,12,.13)}.intro,.section{padding:3.4rem 1.25rem}.intro{border-top:1px solid #ECE5DB}.intro p,.section>div>p{font-size:1rem;line-height:1.8;margin:0 0 1rem}.section h2{font:400 clamp(1.55rem,3.5vw,2.2rem)/1.15 'DM Serif Display',serif;color:#1A1208;letter-spacing:-.02em;margin:0 0 1.1rem}.section h3{font:400 1.35rem/1.2 'DM Serif Display',serif;color:#1A1208;margin:0 0 1rem}.section ol,.section ul{padding-left:1.3rem;line-height:1.75;margin:0 0 2rem}.section li+li{margin-top:.5rem}.tint{background:#FAF7F2}.snapshot,.profiles{display:grid;grid-template-columns:repeat(2,1fr);gap:1rem}.snapshot>div,.profile,.cards section{background:#fff;border:1px solid #E8E0D5;border-radius:14px;padding:1.15rem}.snapshot h3{color:#B06000;font:700 .75rem/1.2 'DM Sans',sans-serif;text-transform:uppercase;letter-spacing:.08em;margin:0 0 .8rem}.snapshot p{font-size:.84rem;line-height:1.6;margin:.55rem 0}.snapshot b,.cards b{display:block;color:#1A1208;font-size:.7rem;text-transform:uppercase;letter-spacing:.06em;margin-bottom:.08rem}.cards{display:grid;grid-template-columns:repeat(2,1fr);gap:.85rem;margin-top:1.3rem}.cards h4,.profile h4{font:400 1.16rem/1.2 'DM Serif Display',serif;color:#1A1208;margin:0 0 .75rem}.cards p{display:grid;grid-template-columns:115px 1fr;gap:.65rem;border-top:1px solid #F0EBE4;padding-top:.58rem;margin:.58rem 0 0;color:#5B4D40;font-size:.8rem;line-height:1.5}.profile-group{margin-top:2.6rem}.profile p{font-size:.84rem;line-height:1.65;margin:.65rem 0}.profile b{color:#1A1208}.dark{background:#1A1208}.dark h2{color:#fff}.dark ol{color:rgba(255,255,255,.78)}
      @media(max-width:700px){.hero{padding-top:2.7rem}.image-shell{padding-bottom:2.25rem}.hero-image{border-radius:13px}.intro,.section{padding:2.6rem 1.05rem}.intro p,.section>div>p{font-size:.95rem;line-height:1.75}.snapshot,.profiles,.cards{grid-template-columns:1fr}.cards p{grid-template-columns:105px 1fr;font-size:.78rem}.profile{padding:1rem}.profile p{font-size:.82rem}.section ol,.section ul{font-size:.92rem}}
    `}</style>
  </>
}
